services:
  redis:
    image: redis:alpine
    container_name: usersdotfun_redis_dev
    ports:
      - '6379:6379'
  postgres:
    image: postgres:16
    container_name: usersdotfun_postgres_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: usersdotfun
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: