import type { PluginSourceItem } from '@usersdotfun/core-sdk';
import type { TelegramMessage, TelegramState } from './schemas';

// The specific type for a source item generated by this plugin.
// The `raw` property will contain the full Telegram message object.
export type TelegramPluginSourceItem = PluginSourceItem<TelegramMessage>;

// Re-exporting the core types for convenience.
export type {
  TelegramSourceConfig,
  TelegramSearchOptions,
  TelegramSourceInput,
  TelegramSourceOutput,
  TelegramState,
  TelegramMessage,
} from './schemas';
