services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  rss-service:
    build: .
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production
      - API_SECRET=${API_SECRET:-change-this-to-a-secure-random-string}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CONTAINER_RUNTIME=true
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis-data:
