[build]
  command = "npm run build"
  publish = "dist"
  functions = "dist"

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"
  included_files = ["!dist/**/*.d.ts", "dist/**/*.js"]
  external_node_modules = ["@netlify/functions"]

# Environment variables
[template.environment]
  API_SECRET = "Secret key for API authentication (should match curate.config.json)"
  UPSTASH_REDIS_REST_URL = "Upstash Redis REST URL"
  UPSTASH_REDIS_REST_TOKEN = "Upstash Redis REST Token"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200
